name: CI Pipeline

on: push

jobs:
    project-testing:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11' 
                cache: "pip" 

            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-south-1  
                    
            - name: Pull DVC data
              run: |
                dvc pull    
                
            - name: run pipeline
              env:
                DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
              run: |
                dvc repro  
                
            - name: model register test and performance
              env:
                DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
              run: |
                pytest tests/test_models.py    

            - name: promote model to production
              if: success()
              env:
                DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
              run: |
                python scripts/promote.py     

            - name: Run Flask app tests
              if: success()
              env:
                DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
              run: |
                pytest tests/test_flask_app.py     

            - name: Login to Docker hub
              if: success()
              uses: docker/login-action@v4
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}    

            - name: Build docker image
              if: success()
              run: |
                docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/emotion2:latest    